"""
Warren Bros — bold restyle for the 8 core inner pages.

These pages are generated by build_pages.py with an OLD embedded CSS block. This script
swaps that <style> block for a bold one (Fraunces + Plus Jakarta, slate-blue brand,
matching the bold homepage) WITHOUT touching markup or content — it targets the same
classes the pages already use. Runs on the served ./site folder so a git push deploys it.

NOTE: build_pages.py's embedded CSS is now stale — after any regeneration, re-run this.
Blog pages (./site/blog/*) are a separate pass (their own embedded CSS + .post-card classes).

Run:  python restyle_inner.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(HERE, "site")

PAGES = [
    "about.html", "contact.html", "faq.html",
    "services/index.html",
    "services/cedar-privacy-fence.html",
    "services/fence-repair.html",
    "services/gate-installation.html",
    "services/fence-removal.html",
]

FONT_LINK = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400..900;1,9..144,400..900&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">'
)

CSS = """
  :root {
    --orange:#e85f2a; --orange-dark:#c14d20; --orange-soft:#fbe7dd;
    --ink:#2c3a4a; --ink-2:#1d2731; --ink-3:#3d4a5c;
    --gold:#f0a830; --green:#2bb24a;
    --cream:#faf4e8; --cream-2:#f3ead7; --text:#23201c; --muted:#6f665b; --line:#e7dccd;
    --radius:18px; --radius-sm:12px; --shadow-sm:0 2px 12px rgba(29,39,49,.06);
    --shadow:0 18px 44px -18px rgba(29,39,49,.26); --ease:cubic-bezier(.22,1,.36,1);
    --display:'Fraunces',Georgia,serif; --sans:'Plus Jakarta Sans','Helvetica Neue',Arial,sans-serif;
    --green-dark:var(--ink); --green-darker:var(--ink-2); --wheat:var(--orange);
  }
  *{box-sizing:border-box;margin:0;padding:0;}
  html{scroll-behavior:smooth;overflow-x:clip;}
  body{font-family:var(--sans);color:var(--text);background:var(--cream);line-height:1.65;font-size:18px;overflow-x:clip;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;}
  h1,h2,h3,h4{font-family:var(--display);font-weight:600;line-height:1.08;letter-spacing:-.015em;font-optical-sizing:auto;}
  a{color:var(--ink);text-decoration:none;} a:hover{text-decoration:underline;}
  img{max-width:100%;}
  .container{max-width:1500px;margin:0 auto;padding:0 32px;}
  .container-narrow{max-width:820px;margin:0 auto;padding:0 24px;}

  /* Header */
  header{background:rgba(250,244,232,.82);backdrop-filter:saturate(160%) blur(14px);-webkit-backdrop-filter:saturate(160%) blur(14px);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:100;}
  .nav{display:flex;align-items:center;justify-content:space-between;padding:14px 40px;max-width:1540px;margin:0 auto;gap:20px;flex-wrap:nowrap;}
  .logo{display:flex;align-items:center;gap:14px;}
  .logo img{height:64px;width:auto;}
  .logo-text small{display:block;font-family:var(--sans);font-size:.68rem;font-weight:700;color:var(--muted);letter-spacing:.16em;text-transform:uppercase;}
  .nav-right{display:flex;align-items:center;gap:24px;flex-wrap:nowrap;}
  .nav-phone{display:inline-flex;align-items:center;gap:10px;font-weight:800;color:var(--orange) !important;font-size:1.22rem;text-decoration:none;white-space:nowrap;}
  .nav-phone:hover{color:var(--orange-dark) !important;text-decoration:none;}
  .nav-phone-icon{width:38px;height:38px;background:linear-gradient(145deg,var(--orange),var(--orange-dark));color:#fff;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;box-shadow:0 6px 14px -5px rgba(232,95,42,.7);}
  .nav-phone-icon svg{width:18px;height:18px;fill:#fff;}
  nav#mainNav>ul{list-style:none;display:flex;gap:28px;align-items:center;}
  nav#mainNav a{color:var(--text);font-family:var(--sans);font-weight:600;font-size:1.02rem;position:relative;}
  nav#mainNav>ul>li>a:not(.cta-btn)::after{content:'';position:absolute;left:0;bottom:-6px;width:100%;height:2px;background:var(--orange);transform:scaleX(0);transform-origin:left;transition:transform .25s var(--ease);}
  nav#mainNav>ul>li>a:not(.cta-btn):hover{text-decoration:none;}
  nav#mainNav>ul>li>a:not(.cta-btn):hover::after{transform:scaleX(1);}
  nav li.has-dropdown{position:relative;}
  nav li.has-dropdown>a::after{content:" \\25BE";font-size:.8em;color:var(--muted);}
  nav li.has-dropdown .dropdown{display:none;position:absolute;top:100%;left:0;min-width:280px;background:#fff;box-shadow:var(--shadow);border-radius:var(--radius-sm);border-top:3px solid var(--orange);padding:8px 0;list-style:none;z-index:200;margin-top:10px;}
  nav li.has-dropdown:hover .dropdown,nav li.has-dropdown:focus-within .dropdown,nav li.has-dropdown.open .dropdown{display:block;}
  nav li.has-dropdown .dropdown a{display:block;padding:11px 22px;font-size:.98rem;color:var(--text);white-space:nowrap;}
  nav li.has-dropdown .dropdown a::after{display:none;}
  nav li.has-dropdown .dropdown a:hover{background:var(--cream);color:var(--orange);text-decoration:none;}
  .cta-btn{background:linear-gradient(145deg,var(--orange),var(--orange-dark));color:#fff !important;padding:12px 24px;border-radius:999px;font-family:var(--sans);font-weight:700;border:none;cursor:pointer;font-size:1rem;display:inline-block;box-shadow:0 10px 22px -10px rgba(232,95,42,.85);transition:transform .2s var(--ease),box-shadow .2s var(--ease),filter .2s;}
  .cta-btn:hover{text-decoration:none;transform:translateY(-2px);filter:brightness(1.04);box-shadow:0 16px 30px -12px rgba(232,95,42,.95);}
  .menu-toggle{display:none;background:none;border:none;font-size:28px;color:var(--ink);cursor:pointer;}

  /* Page hero */
  .page-hero{background:linear-gradient(135deg,var(--ink) 0%,var(--ink-2) 100%);color:#fff;padding:92px 0 84px;text-align:center;position:relative;overflow:hidden;}
  .page-hero::before{content:'';position:absolute;top:-30%;right:-8%;width:55vw;height:55vw;max-width:680px;max-height:680px;background:radial-gradient(circle,rgba(240,168,48,.16),transparent 62%);pointer-events:none;}
  .page-hero .container,.page-hero .container-narrow{position:relative;z-index:1;}
  .page-hero .kicker{display:inline-flex;align-items:center;gap:9px;color:#fff;background:rgba(240,168,48,.16);border:1px solid rgba(240,168,48,.45);padding:7px 16px;border-radius:999px;font-family:var(--sans);font-size:.78rem;font-weight:700;letter-spacing:2px;text-transform:uppercase;margin-bottom:18px;}
  .page-hero .kicker::before{content:'';width:7px;height:7px;border-radius:50%;background:var(--gold);}
  .page-hero h1{font-size:clamp(2.2rem,4.6vw,3.6rem);line-height:1.04;margin-bottom:16px;letter-spacing:-.02em;}
  .page-hero p.lede{font-size:1.2rem;max-width:720px;margin:0 auto;opacity:.94;}
  .page-hero .cta-row{margin-top:28px;display:inline-flex;gap:14px;flex-wrap:wrap;justify-content:center;}
  .page-hero .cta-row a{background:linear-gradient(145deg,var(--orange),var(--orange-dark));color:#fff;padding:15px 28px;border-radius:999px;font-family:var(--sans);font-weight:700;font-size:1.02rem;box-shadow:0 12px 24px -10px rgba(232,95,42,.8);}
  .page-hero .cta-row a.secondary{background:rgba(255,255,255,.08);border:1.5px solid rgba(255,255,255,.55);box-shadow:none;backdrop-filter:blur(4px);}
  .page-hero .cta-row a:hover{text-decoration:none;filter:brightness(1.05);}

  /* Body */
  main section{padding:72px 0;}
  main section.alt{background:var(--cream-2);}
  main h2{font-size:clamp(1.7rem,3vw,2.4rem);color:var(--ink);margin-bottom:18px;line-height:1.12;}
  main h3{font-size:1.3rem;color:var(--ink);margin:28px 0 12px;}
  main p{margin-bottom:16px;}
  main ul,main ol{margin:0 0 18px 22px;} main ul li,main ol li{margin-bottom:8px;}
  main strong{color:var(--ink);}
  .pillars{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:24px;margin-top:28px;}
  .pillar{background:#fff;border:1px solid var(--line);border-left:4px solid var(--orange);padding:26px 26px;border-radius:var(--radius);box-shadow:var(--shadow-sm);transition:transform .3s var(--ease),box-shadow .3s var(--ease);}
  .pillar:hover{transform:translateY(-5px);box-shadow:var(--shadow);}
  .pillar h3{margin-top:0;}
  .pillar h3 a{color:var(--ink);} .pillar h3 a:hover{color:var(--orange);}
  .price-band{background:var(--orange-soft);border:1px solid rgba(232,95,42,.25);border-radius:var(--radius);padding:24px 28px;margin:26px 0;}
  .price-band strong{color:var(--orange-dark);font-size:1.12rem;}

  /* FAQ cards */
  .faq-item{background:#fff;border:1px solid var(--line);border-radius:var(--radius-sm);padding:22px 26px;margin-bottom:14px;box-shadow:var(--shadow-sm);}
  .faq-item h3{margin:0 0 8px;color:var(--ink);font-size:1.2rem;}
  .faq-item p{margin-bottom:0;color:var(--text);}

  /* Contact */
  .contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:start;}
  .contact-info dl{display:grid;grid-template-columns:max-content 1fr;gap:12px 18px;margin-top:8px;}
  .contact-info dt{font-family:var(--sans);font-weight:700;color:var(--ink);}
  .contact-form{background:#fff;padding:34px;border-radius:var(--radius);border:1px solid var(--line);box-shadow:var(--shadow);}
  .contact-form label{display:block;font-family:var(--sans);font-weight:600;margin-bottom:6px;color:var(--ink);font-size:.9rem;}
  .contact-form input,.contact-form textarea{width:100%;padding:12px 15px;border:1.5px solid var(--line);border-radius:var(--radius-sm);font-family:var(--sans);font-size:1rem;margin-bottom:18px;background:var(--cream);transition:border-color .2s,box-shadow .2s,background .2s;}
  .contact-form input:focus,.contact-form textarea:focus{outline:none;border-color:var(--orange);background:#fff;box-shadow:0 0 0 4px rgba(232,95,42,.12);}
  .contact-form textarea{min-height:130px;resize:vertical;}
  .contact-form button{background:linear-gradient(145deg,var(--orange),var(--orange-dark));color:#fff;border:none;padding:15px 28px;border-radius:999px;font-family:var(--sans);font-size:1.05rem;font-weight:700;cursor:pointer;width:100%;box-shadow:0 12px 24px -10px rgba(232,95,42,.85);transition:transform .2s var(--ease),filter .2s;}
  .contact-form button:hover{transform:translateY(-2px);filter:brightness(1.04);}

  /* CTA band */
  .cta-band{background:linear-gradient(135deg,var(--ink) 0%,var(--ink-2) 100%);color:#fff;padding:64px 0;text-align:center;position:relative;overflow:hidden;}
  .cta-band::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 70% 30%,rgba(240,168,48,.16),transparent 55%);pointer-events:none;}
  .cta-band .container,.cta-band .container-narrow{position:relative;z-index:1;}
  .cta-band h2{color:#fff;font-size:clamp(1.8rem,3.4vw,2.6rem);margin-bottom:12px;}
  .cta-band p{font-size:1.1rem;margin-bottom:24px;opacity:.9;max-width:640px;margin-left:auto;margin-right:auto;}
  .cta-band a{background:linear-gradient(145deg,var(--orange),var(--orange-dark));color:#fff !important;padding:15px 30px;border-radius:999px;font-family:var(--sans);font-weight:700;font-size:1.05rem;box-shadow:0 12px 24px -10px rgba(232,95,42,.85);}
  .cta-band a:hover{text-decoration:none;filter:brightness(1.04);}

  /* Footer */
  footer{background:var(--ink-2);color:#c5cabb;padding:64px 0 26px;border-top:4px solid var(--green);}
  .footer-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:44px;}
  footer h4{color:#fff;font-family:var(--display);font-size:1.1rem;margin-bottom:14px;letter-spacing:0;text-transform:none;}
  .footer-logo img{height:60px;margin-bottom:14px;background:#fff;padding:4px;border-radius:12px;}
  footer ul{list-style:none;padding:0;margin:0;} footer li{margin-bottom:8px;}
  footer a{color:#aeb3a4;} footer a:hover{color:var(--orange);text-decoration:none;}
  .footer-bottom{border-top:1px solid rgba(255,255,255,.10);margin-top:36px;padding-top:22px;text-align:center;color:#87897d;font-size:.86rem;}

  @media(max-width:900px){
    .contact-grid{grid-template-columns:1fr;}
    .footer-grid{grid-template-columns:1fr 1fr;gap:28px;}
    nav#mainNav{display:none;position:absolute;top:100%;right:0;left:0;background:#fff;box-shadow:var(--shadow);padding:18px 24px;border-bottom:1px solid var(--line);}
    nav#mainNav.open{display:block;}
    nav#mainNav>ul{flex-direction:column;gap:16px;align-items:flex-start;}
    nav#mainNav>ul>li>a:not(.cta-btn)::after{display:none;}
    nav li.has-dropdown .dropdown{position:static;box-shadow:none;border-top:none;border-left:3px solid var(--orange);border-radius:0;padding:4px 0 4px 14px;margin:8px 0 0;min-width:0;}
    nav li.has-dropdown:hover .dropdown{display:none;}
    nav li.has-dropdown.open .dropdown{display:block;}
    .menu-toggle{display:inline-block;}
  }
  @media(max-width:700px){
    .container,.container-narrow{padding:0 18px;}
    .nav{padding:12px 18px;gap:14px;} .logo img{height:48px;}
    .nav-phone{font-size:1.05rem;} .nav-phone-icon{width:32px;height:32px;}
    main section{padding:54px 0;}
    .footer-grid{grid-template-columns:1fr;}
  }
"""

def main():
    for rel in PAGES:
        p = os.path.join(SITE, rel)
        if not os.path.exists(p):
            print("MISSING:", rel); continue
        html = open(p, encoding="utf-8").read()
        new_html, n = re.subn(r"<style>.*?</style>", lambda m: "<style>\n" + CSS + "\n</style>",
                              html, count=1, flags=re.S)
        if n == 0:
            print("NO <style> FOUND:", rel); continue
        if "fonts.googleapis.com" not in new_html:
            new_html = new_html.replace("</title>", "</title>\n" + FONT_LINK, 1)
        open(p, "w", encoding="utf-8").write(new_html)
        print("restyled:", rel)

if __name__ == "__main__":
    main()
